//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenniesMgt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winner
    {
        public long ID { get; set; }
        public long WinnerID { get; set; }
        public int Point { get; set; }
        public long MatchID { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual User User { get; set; }
    }
}
